// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6PCjnubdRY2SH9txkJm_JqJv3IqyxAU',
    appId: '1:658742941827:web:1db39cef6c5db083f5e3b6',
    messagingSenderId: '658742941827',
    projectId: 'shoppingapp-18cf4',
    authDomain: 'shoppingapp-18cf4.firebaseapp.com',
    storageBucket: 'shoppingapp-18cf4.firebasestorage.app',
    measurementId: 'G-Z8SBERKT51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBid1MaxICKTl2iefWIoTPreyZ-gl-Bb0',
    appId: '1:658742941827:android:9bd326b231bcc87bf5e3b6',
    messagingSenderId: '658742941827',
    projectId: 'shoppingapp-18cf4',
    storageBucket: 'shoppingapp-18cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwG6gz1fYc93Zc9VP1hynTttI4vfyZKL4',
    appId: '1:658742941827:ios:4971445b838591ddf5e3b6',
    messagingSenderId: '658742941827',
    projectId: 'shoppingapp-18cf4',
    storageBucket: 'shoppingapp-18cf4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwG6gz1fYc93Zc9VP1hynTttI4vfyZKL4',
    appId: '1:658742941827:ios:4971445b838591ddf5e3b6',
    messagingSenderId: '658742941827',
    projectId: 'shoppingapp-18cf4',
    storageBucket: 'shoppingapp-18cf4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6PCjnubdRY2SH9txkJm_JqJv3IqyxAU',
    appId: '1:658742941827:web:c3b414a049a55fdcf5e3b6',
    messagingSenderId: '658742941827',
    projectId: 'shoppingapp-18cf4',
    authDomain: 'shoppingapp-18cf4.firebaseapp.com',
    storageBucket: 'shoppingapp-18cf4.firebasestorage.app',
    measurementId: 'G-9KSZNWP45F',
  );
}
